def test_app_fail():
    assert True, "Intentionally failed the testcase"
