def test_app_fail():
    assert False, "Intentionally failed the testcase"
